name: Conda

on:
  workflow_dispatch:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]


    steps:
        - uses: actions/checkout@v3

        - uses: fortran-lang/setup-fortran@v1
          id: setup-fortran
          with:
            compiler: 'intel-classic'
            version: '2021.10'

        - uses: conda-incubator/setup-miniconda@v2
          with:
            miniforge-variant: Mambaforge
            miniforge-version: latest

        - name: Dependencies for conda recipes generation and upload
          shell: bash -l {0}
          run: |
            echo "The fortran compiler configured is $FC"
            # Workaround for https://github.com/conda-incubator/setup-miniconda/issues/186
            conda config --remove channels defaults
            mamba install pyyaml jinja2 conda-build ninja conda-forge-pinning mamba boa multisheller
            
        - name: Print used environment
          shell: bash -l {0}
          run: |
            mamba list
            env
        
        - name: Build conda packages
          shell: bash -l {0}
          run: |
            export GITHUB_ACTION_WD=`pwd`
            cd conda/spral
            conda mambabuild -m ${CONDA_PREFIX}/conda_build_config.yaml .

